-- require("telescope").setup({
--   extensions = {
--     aerial = {
--       -- Set the width of the first two columns (the second
--       -- is relevant only when show_columns is set to 'both')
--       col1_width = 4,
--       col2_width = 30,
--       -- How to format the symbols
--       format_symbol = function(symbol_path, filetype)
--         if filetype == "json" or filetype == "yaml" then
--           return table.concat(symbol_path, ".")
--         else
--           return symbol_path[#symbol_path]
--         end
--       end,
--       -- Available modes: symbols, lines, both
--       show_columns = "both",
--     },
--   },
-- })
-- local actions = require("telescope.actions")
-- local open_with_trouble = require("trouble.sources.telescope").open

-- -- Use this to add more results without clearing the trouble list
-- local add_to_trouble = require("trouble.sources.telescope").add

-- local telescope = require("telescope")

-- telescope.setup({
--   defaults = {
--     mappings = {
--       i = { ["<c-t>"] = open_with_trouble },
--       n = { ["<c-t>"] = open_with_trouble },
--     },
--   },
-- })

-- require "telescope".load_extension("agrolens")
-- require("telescope").extensions = {
--     agrolens = {
--        debug = false,
--        same_type = true,
--        include_hidden_buffers = false,
--        disable_indentation = false,
--        aliases = {}
--     }
-- }